In [1]:
import pandas as pd
import duckdb
import glob

In [36]:
path = "data/energy_charts/public_power_forecast/year=2025/month=09/day=04/*.parquet"
file = glob.glob(path)[0]
dap = pd.read_parquet(file)

In [37]:
dap

,unix_seconds,forecast_values,production_type,forecast_type,deprecated,country,_dlt_load_id,_dlt_id
0,1756936800,44387.6,load,day-ahead,False,de,1756907377.8254762,R6/B/HJafoRh3A
1,1756937700,43797.4,load,day-ahead,None,de,1756907377.8254762,0NklKD1Y4E91dA
2,1756938600,43423.7,load,day-ahead,None,de,1756907377.8254762,UbUGNMQwWDpv1g
3,1756939500,42963.7,load,day-ahead,None,de,1756907377.8254762,P1W9x+z5+ujr2g
4,1756940400,42364.4,load,day-ahead,None,de,1756907377.8254762,iabMCky5v1Al6w
...,...,...,...,...,...,...,...,...
91,1757018700,48453.7,load,day-ahead,None,de,1756907377.8254762,CKYj7L2qXcjCsA
92,1757019600,47679.4,load,day-ahead,None,de,1756907377.8254762,TEL+7Gz+FoD85A
93,1757020500,46751.2,load,day-ahead,None,de,1756907377.8254762,d8xjhXQFIZotKw
94,1757021400,46079.4,load,day-ahead,None,de,1756907377.8254762,qB9MBpEBEAHNqA
95,1757022300,45298.3,load,day-ahead,None,de,1756907377.8254762,EZocoaIVy+91hQ

Show duckDB data

In [94]:
con = duckdb.connect("dbt_project/energydata.duckdb")

In [95]:
con.execute("use analytics_intermediate")

In [96]:
print("Tables:", con.execute("show tables").fetchall())

Tables: [('int_energy_charts__cbet',), ('int_energy_charts__dap',), ('int_energy_charts__ppf',)]

In [86]:
schemas = con.execute("SELECT DISTINCT schema_name FROM information_schema.schemata").fetchall()
print("Schemas:", schemas)

Schemas: [('analytics_staging',), ('analytics_intermediate',), ('pg_catalog',), ('main',), ('information_schema',)]

In [99]:

data = con.execute("select * from int_energy_charts__ppf order by unix_seconds_15min").df()
data

,unix_seconds_15min,forecast_values,production_type,forecast_type,country,_dlt_id
0,1756936800,44387.6,load,day-ahead,de,lSnDt3Fegd0XuQ
1,1756937700,43797.4,load,day-ahead,de,/6R6bCtLPdnvfw
2,1756938600,43423.7,load,day-ahead,de,SAKrG8fiAk8FDg
3,1756939500,42963.7,load,day-ahead,de,4R7MJgMuNMEMJQ
4,1756940400,42364.4,load,day-ahead,de,aXXU4RYQOWqmvQ
...,...,...,...,...,...,...
91,1757018700,48453.7,load,day-ahead,de,t7WbuEsWq5LZJQ
92,1757019600,47679.4,load,day-ahead,de,IKGywYtGdp6xGg
93,1757020500,46751.2,load,day-ahead,de,rqoybbgXDhMtYg
94,1757021400,46079.4,load,day-ahead,de,fTU9cf4Bzg6hkg
95,1757022300,45298.3,load,day-ahead,de,GgcHmZ+l29CXoA

In [100]:
con.close()